name: CI build & test

on:
  push:

  pull_request:
    types: [opened, review_requested]

jobs:   
  build_and_test:
    runs-on: ubuntu-latest   
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install g++ & tools
        run: sudo apt update && sudo apt install -y g++ git

      - name: Compile C++ program
        run: g++ -std=c++17 -o program main.cpp portfolio.cpp cal.cpp

      - name: Run C++ program
        run: ./program

      - name: Install Google Test
        run: |
          git clone https://github.com/google/googletest.git
          g++ -std=c++17 -I googletest/googletest/include -I googletest/googletest -c googletest/googletest/src/gtest-all.cc
          ar -rv libgtest.a gtest-all.o
          sudo mv libgtest.a /usr/lib/
          sudo cp -r googletest/googletest/include/gtest /usr/include/

      - name: Compile Unit Tests
        run: |
           g++ -std=c++17 -I/usr/include -pthread portfolio.cpp portfolio.cpp cal.cpp \
           googletest/googletest/src/gtest_main.cc /usr/lib/libgtest.a -o tests

      - name: Run Unit Tests
        run: ./tests

        

